[workspace]
members = [
    "crates/geom_app",
    "crates/geom_diagnostics",
    "crates/geom_geometry",
    "crates/geom_scene",
    "crates/geom_workspace",
    "crates/geom_workspace_api",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sguzman/morphos"

[workspace.lints.rust]
unsafe_code = "deny"
